// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEW7z8Ur_DaGplSe12m_612Sry5bKPBco',
    appId: '1:255861698408:android:0042ce0f4cea7633abb0dd',
    messagingSenderId: '255861698408',
    projectId: 'fmc-test-app',
    storageBucket: 'fmc-test-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9EB-jGEMjC2TTe80DGvrSZsu16O7gwaM',
    appId: '1:255861698408:ios:c4a918d4fe8f0dceabb0dd',
    messagingSenderId: '255861698408',
    projectId: 'fmc-test-app',
    storageBucket: 'fmc-test-app.appspot.com',
    iosClientId: '255861698408-mtkak3vde3fg7n7hrj4a646plaldv4jq.apps.googleusercontent.com',
    iosBundleId: 'com.fmc-test-app.app',
  );
}
